name: 'Dependency Review'

on:
  pull_request:
    branches: [ "master", 1.*, '2.1[a-zA-Z0-9].*', '2.[a-zA-Z0-9].*' ]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-Review:
    name: Review
    uses: coveo/public-actions/.github/workflows/dependency-review.yml@main
    with:
      public: true
      distributed: true
